In [1]:
import kagglehub

# Download latest version
path = kagglehub.competition_download('nlp-getting-started')

print("Path to competition files:", path)

/opt/python/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to /home/onyxia/.cache/kagglehub/competitions/nlp-getting-started.archive...

100%|██████████| 593k/593k [00:00<00:00, 1.31MB/s]

Extracting files...
Path to competition files: /home/onyxia/.cache/kagglehub/competitions/nlp-getting-started

In [3]:
import os
import kagglehub
import shutil

path = kagglehub.competition_download('nlp-getting-started')
print("Fichiers téléchargés dans :", path)

# Dossier de destination
dest = "data"
os.makedirs(dest, exist_ok=True)

# Copier tous les fichiers du dossier téléchargé vers /data
for fichier in os.listdir(path):
    src_file = os.path.join(path, fichier)
    dst_file = os.path.join(dest, fichier)
    shutil.copy2(src_file, dst_file)

print("Fichiers copiés dans :", dest)

Fichiers téléchargés dans : /home/onyxia/.cache/kagglehub/competitions/nlp-getting-started
Fichiers copiés dans : data

In [4]:
#Library
import pandas as pd

In [7]:
df_train=pd.read_csv("data/train.csv")

In [9]:
df_train.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [10]:
df_train=df_train.drop(columns=['id'])

In [14]:
df_train.head(300)

,keyword,location,text,target
0,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...
295,apocalypse,NaN,Minecraft- NIGHT LUCKY BLOCK MOD (BOB APOCALYP...,0
296,apocalypse,NaN,Shot Through The Heart XV: You are going to to...,0
297,apocalypse,NaN,RT: Geek_Apocalypse: 4pm GMT :Hesse plays dark...,0
298,apocalypse,Las Vegas,I know where to go when the zombies take over!...,0
299,apocalypse,NaN,The latest from @BryanSinger reveals #Storm is...,1

In [16]:
df_train.shape

(7613, 4)

In [21]:
print(df_train['target'].value_counts(normalize=True))

target
0    0.57034
1    0.42966
Name: proportion, dtype: float64

In [23]:
df_train["n_car"]=df_train['text'].str.len()
df_train["n_words"]=df_train['text'].str.split().str.len()

In [26]:
vides=df_train['text'].isna() | (df_train['text']=="")
print(vides.value_counts(normalize=True))

text
False    1.0
Name: proportion, dtype: float64

In [ ]:
print()